// <auto-generated />
using System;
using HeartHealth.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeartHealth.Infrastructure.Migrations
{
    [DbContext(typeof(HeartHealthDbContext))]
    [Migration("20220213231948_AddRequiresVerificationToMeasurement")]
    partial class AddRequiresVerificationToMeasurement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeartHealth.Domain.Entities.History", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("HeartHealth.Domain.Entities.Measurement", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("HistoryId")
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("RequiresVerification")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("HistoryId");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = "f38ebfbb-fe5d-4a51-b709-df6cca17c6f8",
                            RequiresVerification = false,
                            Timestamp = new DateTime(2022, 2, 13, 23, 19, 47, 934, DateTimeKind.Utc).AddTicks(636)
                        },
                        new
                        {
                            Id = "4fba6019-470a-4d12-b268-cd87b614cb83",
                            RequiresVerification = false,
                            Timestamp = new DateTime(2022, 2, 12, 23, 19, 47, 934, DateTimeKind.Utc).AddTicks(648)
                        },
                        new
                        {
                            Id = "26aecce0-383f-440b-9b56-1b5004a70ab7",
                            RequiresVerification = false,
                            Timestamp = new DateTime(2022, 2, 11, 23, 19, 47, 934, DateTimeKind.Utc).AddTicks(721)
                        });
                });

            modelBuilder.Entity("HeartHealth.Domain.Entities.History", b =>
                {
                    b.OwnsOne("HeartHealth.Domain.ValueObjects.BloodPressure", "AverageBloodPressure", b1 =>
                        {
                            b1.Property<string>("HistoryId")
                                .HasColumnType("varchar(36)");

                            b1.Property<int>("Diastolic")
                                .HasColumnType("int")
                                .HasColumnName("AverageDiastolic");

                            b1.Property<int>("Systolic")
                                .HasColumnType("int")
                                .HasColumnName("AverageSystolic");

                            b1.HasKey("HistoryId");

                            b1.ToTable("Histories");

                            b1.WithOwner()
                                .HasForeignKey("HistoryId");
                        });

                    b.OwnsOne("HeartHealth.Domain.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<string>("HistoryId")
                                .HasColumnType("varchar(36)");

                            b1.Property<DateTime>("End")
                                .HasColumnType("smalldatetime")
                                .HasColumnName("End");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("smalldatetime")
                                .HasColumnName("Start");

                            b1.HasKey("HistoryId");

                            b1.ToTable("Histories");

                            b1.WithOwner()
                                .HasForeignKey("HistoryId");
                        });

                    b.Navigation("AverageBloodPressure");

                    b.Navigation("DateRange");
                });

            modelBuilder.Entity("HeartHealth.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("HeartHealth.Domain.Entities.History", null)
                        .WithMany("Measurements")
                        .HasForeignKey("HistoryId");

                    b.OwnsOne("HeartHealth.Domain.ValueObjects.BloodPressure", "BloodPressure", b1 =>
                        {
                            b1.Property<string>("MeasurementId")
                                .HasColumnType("varchar(36)");

                            b1.Property<int>("Diastolic")
                                .HasColumnType("int")
                                .HasColumnName("Diastolic");

                            b1.Property<int>("Systolic")
                                .HasColumnType("int")
                                .HasColumnName("Systolic");

                            b1.HasKey("MeasurementId");

                            b1.ToTable("Measurements");

                            b1.WithOwner()
                                .HasForeignKey("MeasurementId");

                            b1.HasData(
                                new
                                {
                                    MeasurementId = "f38ebfbb-fe5d-4a51-b709-df6cca17c6f8",
                                    Diastolic = 80,
                                    Systolic = 120
                                },
                                new
                                {
                                    MeasurementId = "4fba6019-470a-4d12-b268-cd87b614cb83",
                                    Diastolic = 77,
                                    Systolic = 112
                                },
                                new
                                {
                                    MeasurementId = "26aecce0-383f-440b-9b56-1b5004a70ab7",
                                    Diastolic = 81,
                                    Systolic = 118
                                });
                        });

                    b.Navigation("BloodPressure")
                        .IsRequired();
                });

            modelBuilder.Entity("HeartHealth.Domain.Entities.History", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
